//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-auth-SSD_SERVICE_ID_sd_rnBmVBMNMAATcuPX
import { auth as SSD_SERVICE_ID_sd_rnBmVBMNMAATcuPX } from './sd-services/auth';

export const UserRoutes = [
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-auth-SSD_SERVICE_ID_sd_rnBmVBMNMAATcuPX
SSD_SERVICE_ID_sd_rnBmVBMNMAATcuPX,
];
